plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'me.vihaanvp'
version = '1.0'

sourceCompatibility = '17'
targetCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.formdev:flatlaf:3.4'
}

application {
    mainClass = 'me.vihaanvp.typingspeedtester.Main'
}

shadowJar {
    archiveBaseName = 'TypeSpeedApp'
    archiveClassifier = ''
    archiveVersion = ''
    manifest {
        attributes(
                'Main-Class': 'me.vihaanvp.typingspeedtester.Main'
        )
    }
}

// Fix the dependency issues
distributions {
    main {
        distributionBaseName = 'TypeSpeedApp'
    }
}

distZip.dependsOn shadowJar
distTar.dependsOn shadowJar
startScripts.dependsOn shadowJar